import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col lg:flex-row bg-gray-900 text-white">
          <header className="lg:hidden fixed top-0 left-0 right-0 z-50 bg-gray-800 shadow-md p-4 flex justify-between items-center">
            <h1 className="text-xl font-semibold">NotesApp</h1>
            <nav className="flex gap-4 text-sm">
              <a href="#" className="hover:text-blue-400">
                All Notes
              </a>
              <a href="#" className="hover:text-blue-400">
                Favorites
              </a>
              <a href="#" className="hover:text-blue-400">
                Trash
              </a>
            </nav>
          </header>

          <aside className="hidden lg:flex fixed top-0 left-0 h-full w-64 bg-gray-800 shadow-md flex-col z-40">
            <div className="p-6 font-bold text-2xl border-b border-gray-700">
              NotesApp
            </div>
            <nav className="p-4 space-y-4">
              <Link
                href="/"
                className="block px-4 py-2 rounded hover:bg-gray-700"
              >
                All Notes
              </Link>
              <Link
                href="#"
                className="block px-4 py-2 rounded hover:bg-gray-700"
              >
                Favorites
              </Link>
              <Link
                href="#"
                className="block px-4 py-2 rounded hover:bg-gray-700"
              >
                Trash
              </Link>
            </nav>
          </aside>
          {children}
        </div>
      </body>
    </html>
  );
}
